import { Tag } from "./app/shared/Tag";
import { Food } from "./app/shared/model/Food";

export const sample_foods : Food[] =[
    {
        id:'1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 270,
        favorite: false,
        origins: ['Italy'],
        stars: 4.5,
        imageUrl: 'assets/food-1.jpeg',
        tags: ['Pizza'],
      },
      {
        id:'2',
        name: 'Meatball',
        price: 200,
        cookTime: '20-30',
        favorite: true,
        origins: ['Persia', 'MiddleEast', 'China'],
        stars: 4.7,
        imageUrl: 'assets/food-2.jpg',
        tags: ['Dinner'],
      },
      {
        id:'3',
        name: 'Hamburger',
        price: 175,
        cookTime: '10-15',
        favorite: false,
        origins: ['Germany', 'Us'],
        stars: 3.5,
        imageUrl: 'assets/food-3.jpg',
        tags: ['Burger'],
      },
      {
        id:'4',
        name: 'Fried Potatoes',
        price: 150,
        cookTime: '15-20',
        favorite: true,
        origins: ['Belgium', 'France'],
        stars: 3.3,
        imageUrl: 'assets/food-4.jpg',
        tags: ['Fry'],
      },
      {
        id:'5',
        name: 'Chicken Soup',
        price: 100,
        cookTime: '40-50',
        favorite: false,
        origins: ['India', 'Asia'],
        stars: 3.0,
        imageUrl: 'assets/food-5.jpg',
        tags: ['Soup'],
      },
      {
        id:'6',
        name: 'Vegetables Pizza',
        price: 180,
        cookTime: '40-50',
        favorite: false,
        origins: ['Italy'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tags: ['Pizza'],
      },
      {
        id:'7',
        name: 'Spicy Cheese Burger',
        price: 120,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian'],
        stars: 4.0,
        imageUrl: 'assets/food-7.jpg',
        tags: ['Burger'],
      },
      {
        id:'8',
        name: 'Vegetables Magento Pizza',
        price: 250,
        cookTime: '45-50',
        favorite: false,
        origins: ['Indian'],
        stars: 4.0,
        imageUrl: 'assets/food-8.jpg',
        tags: ['Pizza'],
      },
      {
        id:'9',
        name: 'Chicken Biriyani',
        price: 200,
        cookTime: '45-50',
        favorite: true,
        origins: ['Indian'],
        stars: 4.5,
        imageUrl: 'assets/food-9.jpeg',
        tags: ['FastFood', 'Lunch'],
      },
      {
        id:'10',
        name: 'Pasta',
        price: 150,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian','chinese','Italy'],
        stars: 3.8,
        imageUrl: 'assets/food-10.jpeg',
        tags: ['FastFood', 'Lunch'],
      },
      {
        id:'11',
        name: 'Chicken Kebab',
        price: 180,
        cookTime: '30-45',
        favorite: true,
        origins: ['Indian','Asia','chinese'],
        stars: 4.0,
        imageUrl: 'assets/food-11.jpeg',
        tags: ['FastFood','Lunch'],
      },
      {
        id:'12',
        name: 'Paneer',
        price: 100,
        cookTime: '20-35',
        favorite: false,
        origins: ['Indian'],
        stars: 4.0,
        imageUrl: 'assets/food-12.jpeg',
        tags: ['Dinner'],
      },
      {
        id:'13',
        name: 'Vegetable Soup',
        price: 70,
        cookTime: '15-20',
        favorite: false,
        origins: ['Indian'],
        stars: 4.0,
        imageUrl: 'assets/food-13.jpeg',
        tags: ['Soup'],
      },
      {
        id:'14',
        name: 'Chinese Soup Noodles',
        price: 160,
        cookTime: '20-35',
        favorite: false,
        origins: ['Chinese'],
        stars: 4.0,
        imageUrl: 'assets/food-15.jpeg',
        tags: ['Soup'],
      },
      {
        id:'15',
        name: 'Spicy Chicken',
        price: 140,
        cookTime: '20-35',
        favorite: true,
        origins: ['Indian'],
        stars: 4.0,
        imageUrl: 'assets/food-14.jpeg',
        tags: ['Fry'],
      },
      {
        id:'16',
        name: 'Chicken Roll',
        price: 120,
        cookTime: '20-30',
        favorite: false,
        origins: ['Indian'],
        stars: 4.0,
        imageUrl: 'assets/food-16.jpeg',
        tags: ['Fry'],
      },
      {
        id:'17',
        name: 'Fish Fry',
        price: 100,
        cookTime: '20-35',
        favorite: true,
        origins: ['Indian'],
        stars: 4.2,
        imageUrl: 'assets/food-17.jpeg',
        tags: ['Fry'],
      },
      {
        id:'18',
        name: 'Cheese Balls',
        price: 80,
        cookTime: '20-30',
        favorite: true,
        origins: ['Indian'],
        stars: 4.1,
        imageUrl: 'assets/food-18.jpeg',
        tags: ['Fry'],
      },
      {
        id:'19',
        name: 'Prawn Fry',
        price: 145,
        cookTime: '30-45',
        favorite: true,
        origins: ['Indian'],
        stars: 4.6,
        imageUrl: 'assets/food-19.jpeg',
        tags: ['Fry'],
      },
      {
        id:'20',
        name: 'Chicken Nuggets',
        price: 100,
        cookTime: '20-35',
        favorite: true,
        origins: ['Indian'],
        stars: 4.5,
        imageUrl: 'assets/food-20.jpeg',
        tags: ['Fry'],
      },
      {
        id:'21',
        name: 'Idly',
        price: 40,
        cookTime: '20-35',
        favorite: true,
        origins: ['India','South India'],
        stars: 4.5,
        imageUrl: 'assets/food-21.jpeg',
        tags: ['Dinner'],
      },
       {
        id:'22',
        name: 'Dosai',
        price: 60,
        cookTime: '15-20',
        favorite: true,
        origins: ['India','South India'],
        stars: 4.3,
        imageUrl: 'assets/food-22.jpeg',
        tags: ['Dinner'],
      },
      {
        id:'23',
        name: 'Poori',
        price: 50,
        cookTime: '20-35',
        favorite: true,
        origins: ['India','South India'],
        stars: 4.2,
        imageUrl: 'assets/food-23.jpeg',
        tags: ['Dinner'],
      },
      {
        id:'24',
        name: 'Parotta',
        price: 70,
        cookTime: '30-45',
        favorite: true,
        origins: ['India','South India'],
        stars: 4.5,
        imageUrl: 'assets/food-24.jpeg',
        tags: ['Dinner'],
      },
      {
        id:'25',
        name: 'Chapati',
        price: 65,
        cookTime: '20-35',
        favorite: true,
        origins: ['India','South India'],
        stars: 4.5,
        imageUrl: 'assets/food-25.jpeg',
        tags: ['Dinner'],
      },
      {
        id:'26',
        name: 'Pongal',
        price: 60,
        cookTime: '25-40',
        favorite: false,
        origins: ['India','South India'],
        stars: 4.5,
        imageUrl: 'assets/food-26.jpg',
        tags: ['Dinner'],
      },
      {
        id:'27',
        name: 'Shawarma',
        price: 120,
        cookTime: '20-35',
        favorite: true,
        origins: ['Indian','Asia'],
        stars: 4.5,
        imageUrl: 'assets/food-27.jpeg',
        tags: ['FastFood'],
      },
      {
        id:'28',
        name: 'Hot Dog',
        price: 180,
        cookTime: '20-45',
        favorite: false,
        origins: ['Indian','Asia','USA'],
        stars: 4.2,
        imageUrl: 'assets/food-28.jpg',
        tags: ['FastFood'],
      },
      {
        id:'29',
        name: 'Sandwich',
        price: 90,
        cookTime: '20-35',
        favorite: false,
        origins: ['Indian','Asia'],
        stars: 4.0,
        imageUrl: 'assets/food-29.jpg',
        tags: ['FastFood'],
      },
      {
        id:'30',
        name: 'Chicken Rice',
        price: 100,
        cookTime: '30-45',
        favorite: true,
        origins: ['Indian'],
        stars: 4.9,
        imageUrl: 'assets/food-30.jpeg',
        tags: ['Lunch'],
      },

]

export const sample_tags:Tag[] = [
  { name: 'All', count: 30  },
  { name: 'FastFood', count: 6 },
  { name: 'Pizza', count: 3 },
  { name: 'Lunch', count: 4 },
  { name: 'Dinner', count: 8 },
  { name: 'Burger', count: 2 },
  { name: 'Fry', count: 7 },
  { name: 'Soup', count: 3 },
]

